export const STARTING_BALANCE = 1000;
export const MIN_BET = 1;
export const DEFAULT_LIQUIDITY = 100;
export const ROOM_CODE_LENGTH = 4;
export const ROOM_CODE_CHARS = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
